# Generated by Django 2.1.2 on 2018-11-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='weight_status',
            field=models.BooleanField(default=True, verbose_name='体重记录状态'),
        ),
    ]
