# Generated by Django 2.1.2 on 2018-11-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_outcome', models.BooleanField(default=True, verbose_name='是否为收入')),
                ('description', models.TextField(verbose_name='描述')),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='收入/支出金额')),
                ('record_time', models.DateTimeField(verbose_name='date_published')),
                ('cost_status', models.BooleanField(default=True, verbose_name='消费记录状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
    ]
