# Generated by Django 2.1.2 on 2018-10-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_status', models.BooleanField(default=True, verbose_name='目标状态')),
                ('goal_name', models.CharField(max_length=255, verbose_name='目标名')),
                ('goal_type', models.IntegerField(default=0, verbose_name='目标类型')),
                ('inspiration', models.TextField(null=True, verbose_name='激励语')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('repeat_time', models.CharField(default='MON, TUE, WED, THU, FRI, SAT, SUN,', max_length=255, verbose_name='重复时间')),
                ('total_day', models.IntegerField(default=0, verbose_name='总天数')),
                ('is_reminding', models.BooleanField(default=False, verbose_name='是否开启提醒')),
                ('reminding_time', models.TimeField(null=True, verbose_name='提醒时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
    ]
