# Generated by Django 2.1.2 on 2018-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0002_auto_20181031_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
