# Generated by Django 2.1.2 on 2018-11-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0004_auto_20181109_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='repeat_time',
            field=models.CharField(default='0123456,', max_length=255, null=True, verbose_name='重复时间'),
        ),
    ]
