# Generated by Django 2.1.2 on 2018-11-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0005_auto_20181110_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='total_day',
        ),
        migrations.AddField(
            model_name='goal',
            name='recorded_times',
            field=models.IntegerField(default=0, verbose_name='总天数'),
        ),
    ]
