# Generated by Django 2.1.2 on 2018-11-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0002_auto_20181101_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_image',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_position',
        ),
    ]
